import { NextRequest, NextResponse } from 'next/server'
import { Resend } from 'resend'

const resend = new Resend(process.env.RESEND_API_KEY)
const FROM_EMAIL = process.env.FROM_EMAIL || 'noreply@ajnova.com'

export async function POST(request: NextRequest) {
  try {
    const { calculation, recipientEmail } = await request.json()

    if (!calculation || !recipientEmail) {
      return NextResponse.json(
        { success: false, error: 'Missing required fields' },
        { status: 400 }
      )
    }

    // Generate email HTML
    const emailHTML = generateEmailHTML(calculation)

    // Send email with Resend
    const { data, error } = await resend.emails.send({
      from: FROM_EMAIL,
      to: recipientEmail,
      subject: 'Your ECTS Calculation Report - AJ NOVA',
      html: emailHTML,
    })

    if (error) {
      console.error('Resend error:', error)
      return NextResponse.json(
        { success: false, error: error.message },
        { status: 500 }
      )
    }

    return NextResponse.json({ success: true, data })
  } catch (error: any) {
    console.error('Email API error:', error)
    return NextResponse.json(
      { success: false, error: error.message || 'Failed to send email' },
      { status: 500 }
    )
  }
}

function generateEmailHTML(calculation: any): string {
  const { studentInfo, degreeDetails, result } = calculation

  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <style>
    body {
      font-family: Arial, sans-serif;
      line-height: 1.6;
      color: #333;
      max-width: 600px;
      margin: 0 auto;
      padding: 20px;
    }
    .header {
      background: linear-gradient(135deg, #2563eb 0%, #f25c45 100%);
      color: white;
      padding: 30px;
      text-align: center;
      border-radius: 10px 10px 0 0;
    }
    .header h1 {
      margin: 0 0 10px 0;
      font-size: 28px;
    }
    .content {
      background: #f9fafb;
      padding: 30px;
      border: 1px solid #e5e7eb;
    }
    .result-box {
      background: white;
      border: 2px solid #2563eb;
      border-radius: 10px;
      padding: 25px;
      text-align: center;
      margin: 20px 0;
    }
    .result-box .ects {
      font-size: 48px;
      font-weight: bold;
      color: #2563eb;
      margin: 10px 0;
    }
    .info-section {
      background: white;
      padding: 20px;
      border-radius: 8px;
      margin: 15px 0;
    }
    .info-section h3 {
      color: #1f2937;
      margin-top: 0;
      border-bottom: 2px solid #f25c45;
      padding-bottom: 10px;
    }
    .info-row {
      display: flex;
      justify-content: space-between;
      padding: 8px 0;
      border-bottom: 1px solid #e5e7eb;
    }
    .info-label {
      font-weight: 600;
      color: #6b7280;
    }
    .warning-box {
      background: #fffbeb;
      border-left: 4px solid #fbbf24;
      padding: 15px;
      margin: 20px 0;
      border-radius: 5px;
    }
    .warning-box strong {
      color: #92400e;
    }
    .cta-button {
      display: inline-block;
      background: #f25c45;
      color: white;
      padding: 15px 30px;
      text-decoration: none;
      border-radius: 8px;
      font-weight: 600;
      margin: 20px 0;
    }
    .footer {
      text-align: center;
      padding: 20px;
      color: #6b7280;
      font-size: 14px;
      border-top: 1px solid #e5e7eb;
      margin-top: 30px;
    }
  </style>
</head>
<body>
  <div class="header">
    <h1>🎓 ECTS Calculation Report</h1>
    <p>Generated by AJ NOVA</p>
  </div>

  <div class="content">
    <p>Hi ${studentInfo.name},</p>
    <p>Here is your ECTS calculation summary:</p>

    <div class="result-box">
      <p style="margin: 0; color: #6b7280; font-size: 14px; text-transform: uppercase; letter-spacing: 1px;">Estimated ECTS Credits</p>
      <div class="ects">${result.totalECTS}</div>
      <p style="margin: 0; color: #6b7280;">ECTS</p>
      <p style="margin-top: 15px; font-weight: 600; color: #1f2937;">Level: ${result.level}</p>
      <p style="color: #6b7280; font-size: 14px;">Confidence: ${result.confidence}</p>
    </div>

    <div class="info-section">
      <h3>Student Information</h3>
      <div class="info-row">
        <span class="info-label">Name:</span>
        <span>${studentInfo.name}</span>
      </div>
      <div class="info-row">
        <span class="info-label">Country:</span>
        <span>${studentInfo.country.name}</span>
      </div>
    </div>

    <div class="info-section">
      <h3>Calculation Details</h3>
      <div class="info-row">
        <span class="info-label">Formula Used:</span>
        <span>${result.formulaUsed}</span>
      </div>
      <div class="info-row">
        <span class="info-label">Confidence Level:</span>
        <span>${result.confidence}</span>
      </div>
    </div>

    <div class="warning-box">
      <p style="margin: 0;"><strong>Important:</strong> This is an unofficial estimation. All international credentials MUST be officially evaluated by <a href="https://www.uni-assist.de" style="color: #f25c45;">uni-assist</a>. Final ECTS recognition is determined by individual German universities.</p>
    </div>

    <center>
      <a href="${process.env.NEXT_PUBLIC_APP_URL || 'https://www.ajnova.com'}/ects-calculator" class="cta-button">
        View Full Calculator
      </a>
    </center>

    <p>Need help with your German university application? Our expert counsellors are here to assist you every step of the way!</p>
  </div>

  <div class="footer">
    <p><strong>AJ NOVA</strong></p>
    <p>Your Gateway to German Education</p>
    <p style="font-size: 12px; color: #9ca3af;">
      This email was sent because you requested an ECTS calculation report.<br>
      © ${new Date().getFullYear()} AJ NOVA. All rights reserved.
    </p>
  </div>
</body>
</html>
  `
}
