/**
 * ECTS Export Utilities
 * PDF generation for ECTS calculation reports
 */

import jsPDF from 'jspdf'
import { ECTSCalculation, DegreeDetails } from './ects-types'
import { UNI_ASSIST_DISCLAIMER } from './ects-config'

/**
 * Export ECTS calculation to PDF
 */
export async function exportECTSToPDF(calculation: ECTSCalculation): Promise<void> {
  const pdf = new jsPDF()
  const pageWidth = pdf.internal.pageSize.getWidth()
  const pageHeight = pdf.internal.pageSize.getHeight()
  const margin = 20
  const maxWidth = pageWidth - margin * 2
  let yPosition = 20

  // ============================================
  // HEADER
  // ============================================
  pdf.setFontSize(20)
  pdf.setFont('helvetica', 'bold')
  pdf.setTextColor(37, 99, 235) // Blue color
  pdf.text('ECTS Calculation Report', pageWidth / 2, yPosition, { align: 'center' })
  yPosition += 12

  // AJ NOVA Branding
  pdf.setFontSize(10)
  pdf.setTextColor(100)
  pdf.setFont('helvetica', 'normal')
  pdf.text('Generated by AJ NOVA', pageWidth / 2, yPosition, { align: 'center' })
  yPosition += 5
  pdf.text('www.ajnova.com', pageWidth / 2, yPosition, { align: 'center' })
  yPosition += 15

  // Divider line
  pdf.setDrawColor(200)
  pdf.line(margin, yPosition, pageWidth - margin, yPosition)
  yPosition += 12

  // ============================================
  // STUDENT INFORMATION SECTION
  // ============================================
  pdf.setFontSize(14)
  pdf.setFont('helvetica', 'bold')
  pdf.setTextColor(0)
  pdf.text('Student Information', margin, yPosition)
  yPosition += 8

  pdf.setFontSize(10)
  pdf.setFont('helvetica', 'normal')
  pdf.text(`Name: ${calculation.studentInfo.name}`, margin + 5, yPosition)
  yPosition += 6

  if (calculation.studentInfo.email) {
    pdf.text(`Email: ${calculation.studentInfo.email}`, margin + 5, yPosition)
    yPosition += 6
  }

  pdf.text(`Country of Education: ${calculation.studentInfo.country.name}`, margin + 5, yPosition)
  yPosition += 10

  // ============================================
  // DEGREE DETAILS SECTION
  // ============================================
  pdf.setFontSize(14)
  pdf.setFont('helvetica', 'bold')
  pdf.text('Degree Information', margin, yPosition)
  yPosition += 8

  pdf.setFontSize(10)
  pdf.setFont('helvetica', 'normal')

  // Format degree details based on type
  const degreeLines = formatDegreeDetailsForPDF(calculation.degreeDetails)
  degreeLines.forEach(line => {
    pdf.text(line, margin + 5, yPosition)
    yPosition += 6
  })
  yPosition += 8

  // ============================================
  // RESULT BOX (Highlighted)
  // ============================================
  const boxHeight = 45
  const boxY = yPosition

  // Draw colored background based on confidence
  const bgColor = getConfidenceColor(calculation.result.confidence)
  pdf.setFillColor(bgColor.r, bgColor.g, bgColor.b)
  pdf.roundedRect(margin, boxY, maxWidth, boxHeight, 3, 3, 'F')

  yPosition = boxY + 10

  // ECTS Value (Large and prominent)
  pdf.setFontSize(28)
  pdf.setFont('helvetica', 'bold')
  pdf.setTextColor(0)
  pdf.text(`${calculation.result.totalECTS} ECTS`, pageWidth / 2, yPosition, { align: 'center' })
  yPosition += 10

  // Level
  pdf.setFontSize(12)
  pdf.setFont('helvetica', 'normal')
  pdf.text(`Level: ${calculation.result.level}`, pageWidth / 2, yPosition, { align: 'center' })
  yPosition += 8

  // Confidence
  const confidenceBadge = `Confidence: ${calculation.result.confidence}`
  pdf.setFontSize(10)
  pdf.text(confidenceBadge, pageWidth / 2, yPosition, { align: 'center' })
  yPosition += boxHeight - 28 + 12

  // ============================================
  // CALCULATION METHOD SECTION
  // ============================================
  pdf.setFontSize(14)
  pdf.setFont('helvetica', 'bold')
  pdf.setTextColor(0)
  pdf.text('Calculation Method', margin, yPosition)
  yPosition += 8

  pdf.setFontSize(10)
  pdf.setFont('helvetica', 'normal')
  pdf.text(`Formula: ${calculation.result.formulaUsed}`, margin + 5, yPosition)
  yPosition += 6

  const confidenceDesc = getConfidenceDescription(calculation.result.confidence)
  const confidenceLines = pdf.splitTextToSize(confidenceDesc, maxWidth - 10)
  confidenceLines.forEach((line: string) => {
    pdf.text(line, margin + 5, yPosition)
    yPosition += 5
  })
  yPosition += 10

  // ============================================
  // ADMIN OVERRIDE (if applicable)
  // ============================================
  if (calculation.result.adminOverride) {
    const overrideBoxHeight = 25

    // Warning background
    pdf.setFillColor(255, 250, 205) // Light yellow
    pdf.roundedRect(margin, yPosition, maxWidth, overrideBoxHeight, 3, 3, 'F')

    yPosition += 8
    pdf.setFontSize(12)
    pdf.setFont('helvetica', 'bold')
    pdf.text('Administrative Override Applied', margin + 5, yPosition)
    yPosition += 7

    pdf.setFontSize(10)
    pdf.setFont('helvetica', 'normal')
    pdf.text(`Adjusted ECTS: ${calculation.result.adminOverride.overriddenValue}`, margin + 5, yPosition)
    yPosition += 6

    const reasonLines = pdf.splitTextToSize(
      `Reason: ${calculation.result.adminOverride.reason}`,
      maxWidth - 10
    )
    reasonLines.forEach((line: string) => {
      pdf.text(line, margin + 5, yPosition)
      yPosition += 5
    })
    yPosition += 10
  }

  // ============================================
  // GENERATION DATE
  // ============================================
  pdf.setFontSize(9)
  pdf.setTextColor(120)
  pdf.text(
    `Report generated on: ${new Date(calculation.createdAt).toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
    })}`,
    margin,
    yPosition
  )

  // ============================================
  // PAGE 2: FULL DISCLAIMER
  // ============================================
  pdf.addPage()
  yPosition = 20

  pdf.setFontSize(16)
  pdf.setFont('helvetica', 'bold')
  pdf.setTextColor(220, 53, 69) // Red color
  pdf.text('IMPORTANT DISCLAIMER', pageWidth / 2, yPosition, { align: 'center' })
  yPosition += 15

  pdf.setFontSize(10)
  pdf.setFont('helvetica', 'normal')
  pdf.setTextColor(0)

  const disclaimerLines = pdf.splitTextToSize(UNI_ASSIST_DISCLAIMER, maxWidth)
  disclaimerLines.forEach((line: string) => {
    if (yPosition > pageHeight - margin) {
      pdf.addPage()
      yPosition = margin
    }
    pdf.text(line, margin, yPosition)
    yPosition += 5
  })

  // ============================================
  // FOOTER (on all pages)
  // ============================================
  const pageCount = pdf.getNumberOfPages()
  for (let i = 1; i <= pageCount; i++) {
    pdf.setPage(i)
    pdf.setFontSize(8)
    pdf.setTextColor(150)

    const footerY = pageHeight - 10
    pdf.text('Generated by AJ NOVA - www.ajnova.com', pageWidth / 2, footerY, { align: 'center' })

    // Page number
    if (pageCount > 1) {
      pdf.text(`Page ${i} of ${pageCount}`, pageWidth - margin, footerY, { align: 'right' })
    }
  }

  // ============================================
  // SAVE PDF
  // ============================================
  const fileName = `ECTS_Report_${calculation.studentInfo.name.replace(/\s+/g, '_')}_${
    new Date().toISOString().split('T')[0]
  }.pdf`

  pdf.save(fileName)
}

/**
 * Format degree details for PDF display
 */
function formatDegreeDetailsForPDF(degreeDetails: DegreeDetails): string[] {
  const lines: string[] = []

  switch (degreeDetails.type) {
    case 'EU_ECTS':
      lines.push(`Total Credit Points (CP): ${degreeDetails.creditPoints}`)
      if (degreeDetails.subjects && degreeDetails.subjects.length > 0) {
        lines.push('Subject Breakdown:')
        degreeDetails.subjects.forEach(subject => {
          lines.push(`  • ${subject.subjectName}: ${subject.credits} CP`)
        })
      }
      break

    case 'INDIA_SUBCONTINENT':
      const degreeTypeLabel = degreeDetails.degreeType.replace(/_/g, ' ')
      lines.push(`Degree Type: ${degreeTypeLabel}`)
      if (degreeDetails.yearOfCompletion) {
        lines.push(`Year of Completion: ${degreeDetails.yearOfCompletion}`)
      }
      break

    case 'USA_CANADA':
      lines.push(`US Semester Credits: ${degreeDetails.usCredits}`)
      lines.push(`Degree Level: ${degreeDetails.degreeLevel}`)
      break

    case 'UK':
      lines.push(`UK Credits: ${degreeDetails.ukCredits}`)
      lines.push(`Degree Level: ${degreeDetails.degreeLevel}`)
      break

    case 'OTHER':
      lines.push(`Years of Study: ${degreeDetails.yearsCompleted}`)
      lines.push(`Degree Level: ${degreeDetails.degreeLevel}`)
      break
  }

  return lines
}

/**
 * Get background color for confidence level
 */
function getConfidenceColor(confidence: string): { r: number; g: number; b: number } {
  switch (confidence) {
    case 'HIGH':
      return { r: 220, g: 252, b: 231 } // Green tint
    case 'MEDIUM':
      return { r: 254, g: 249, b: 195 } // Yellow tint
    case 'LOW':
      return { r: 254, g: 226, b: 226 } // Red tint
    default:
      return { r: 240, g: 240, b: 255 } // Light blue
  }
}

/**
 * Get confidence level description
 */
function getConfidenceDescription(confidence: string): string {
  switch (confidence) {
    case 'HIGH':
      return 'High confidence - This calculation uses standardized conversion rates that are widely accepted by German universities.'
    case 'MEDIUM':
      return 'Medium confidence - This calculation uses recognized conversion formulas, but actual recognition may vary by institution.'
    case 'LOW':
      return 'Low confidence - This is a rough estimation. Official evaluation by uni-assist is strongly recommended for accurate assessment.'
    default:
      return ''
  }
}

/**
 * Generate PDF as buffer (for email attachments)
 * Returns a Promise that resolves to a buffer
 */
export async function generateECTSPDFBuffer(calculation: ECTSCalculation): Promise<Buffer> {
  const pdf = new jsPDF()
  const pageWidth = pdf.internal.pageSize.getWidth()
  const pageHeight = pdf.internal.pageSize.getHeight()
  const margin = 20
  const maxWidth = pageWidth - margin * 2
  let yPosition = 20

  // Same content as exportECTSToPDF but return as buffer
  // [Duplicate the PDF generation logic above but use pdf.output('arraybuffer')]

  // For now, simplified version - in production, extract the PDF generation into a shared function
  const pdfOutput = pdf.output('arraybuffer')
  return Buffer.from(pdfOutput)
}
