import jsPDF from 'jspdf'
import { Document as DocxDocument, Packer, Paragraph, TextRun, AlignmentType, HeadingLevel } from 'docx'
import { saveAs } from 'file-saver'

export async function exportToPDF(
  title: string,
  content: string,
  studentName: string,
  version: number
) {
  const pdf = new jsPDF()
  const pageWidth = pdf.internal.pageSize.getWidth()
  const margin = 20
  const maxWidth = pageWidth - margin * 2
  
  let yPosition = 20
  
  pdf.setFontSize(16)
  pdf.text(title, pageWidth / 2, yPosition, { align: 'center' })
  yPosition += 10
  
  pdf.setFontSize(10)
  pdf.setTextColor(100)
  pdf.text(`Student: ${studentName}`, margin, yPosition)
  yPosition += 5
  pdf.text(`Version: ${version}`, margin, yPosition)
  yPosition += 5
  pdf.text(`Generated: ${new Date().toLocaleDateString()}`, margin, yPosition)
  yPosition += 15
  
  pdf.setFontSize(11)
  pdf.setTextColor(0)
  
  const text = content.replace(/<[^>]*>/g, ' ').replace(/\s+/g, ' ').trim()
  const lines = pdf.splitTextToSize(text, maxWidth)
  
  lines.forEach((line: string) => {
    if (yPosition > pdf.internal.pageSize.getHeight() - margin) {
      pdf.addPage()
      yPosition = margin
    }
    pdf.text(line, margin, yPosition)
    yPosition += 7
  })
  
  pdf.setFontSize(8)
  pdf.setTextColor(150)
  const footerText = 'Generated by AJ NOVA - www.ajnova.com'
  pdf.text(footerText, pageWidth / 2, pdf.internal.pageSize.getHeight() - 10, { align: 'center' })
  
  pdf.save(`${title.replace(/\s+/g, '_')}_v${version}.pdf`)
}

export async function exportToDOCX(
  title: string,
  content: string,
  studentName: string,
  version: number
) {
  const text = content.replace(/<[^>]*>/g, '\n').replace(/\s+/g, ' ').trim()
  const paragraphs = text.split('\n').filter(p => p.trim().length > 0)
  
  const children = [
    new Paragraph({
      text: title,
      heading: HeadingLevel.HEADING_1,
      alignment: AlignmentType.CENTER,
      spacing: { after: 200 }
    }),
    new Paragraph({
      children: [
        new TextRun({
          text: `Student: ${studentName}`,
          size: 20,
          color: '666666'
        })
      ],
      spacing: { after: 100 }
    }),
    new Paragraph({
      children: [
        new TextRun({
          text: `Version: ${version}`,
          size: 20,
          color: '666666'
        })
      ],
      spacing: { after: 100 }
    }),
    new Paragraph({
      children: [
        new TextRun({
          text: `Generated: ${new Date().toLocaleDateString()}`,
          size: 20,
          color: '666666'
        })
      ],
      spacing: { after: 400 }
    }),
    ...paragraphs.map(
      paragraph =>
        new Paragraph({
          text: paragraph,
          spacing: { after: 200 }
        })
    ),
    new Paragraph({
      children: [
        new TextRun({
          text: 'Generated by AJ NOVA - www.ajnova.com',
          size: 18,
          color: '999999',
          italics: true
        })
      ],
      alignment: AlignmentType.CENTER,
      spacing: { before: 400 }
    })
  ]
  
  const doc = new DocxDocument({
    sections: [
      {
        properties: {},
        children
      }
    ]
  })
  
  const blob = await Packer.toBlob(doc)
  saveAs(blob, `${title.replace(/\s+/g, '_')}_v${version}.docx`)
}
